[project]
name = "scoracle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=1.0.5",
    "llama-index>=0.12.31",
    "openai>=1.75.0",
    "sentence-transformers>=4.1.0",
    "streamlit>=1.44.1",
]
